---
# remove previously installed go and install go
# reference: https://go.dev/doc/install
- name: Download go
  get_url:
    url: "{{go_download_url}}/go{{go_version}}.{{go_os}}-{{go_arch}}.tar.gz"
    dest: "{{go_download_dest_path}}"
  tags:
  - install
- name: Remove any previously installed go version
  become: true
  file:
    path: "{{go_path}}"
    state: absent
  tags:
  - install
- name: Install go
  become: true
  shell: |
    tar -C /usr/local -xzf {{go_download_dest_path}}/go{{go_version}}.{{go_os}}-{{go_arch}}.tar.gz
  tags:
  - install
- name: Remove go installer
  become: true
  file:
    path: "{{go_download_dest_path}}/go{{go_version}}.{{go_os}}-{{go_arch}}.tar.gz"
    state: absent
  tags:
  - install